spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:test}?autoReconnect=true&setTimezone=Asia/Seoul
    username: ${DB_USERNAME:test} # username
    password: ${DB_PASSWORD:example} # password
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
logging.level:
  org.hibernate.SQL: debug